on: pull_request

jobs:
  validate:
    name: Validate build
    runs-on: ubuntu-latest
    steps:
    - name: Checkout spdx-spec
      uses: actions/checkout@eef61447b9ff4aafe5dcd4e0bbf5d482be7e7871  #v4.2.1
      with:
        fetch-depth: 1
    - name: Set up specific Python version
      uses: actions/setup-python@f677139bbe7f9c59b41e40162b753c062f5d49a3  #v5.2.0
      with:
        python-version: "3.12"
        cache: "pip"
    - name: Install pre-requisites
      run: pip install -r requirements.txt
    - name: Build the site to validate (use mkdocs.yml, no model files, no PDF export)
      run: ENABLE_PDF_EXPORT=0 mkdocs build --clean --verbose
      # To validate the PR from within spdx-spec repo, build using mkdocs.yml
      # (no model files) and without the time-consuming PDF export
